version: "3.3"

services:
  api:
    build: ../../service
    container_name: api
    ports:
      - 8084:8084
    command:
      - uvicorn
      - main:app
      - --host
      - '0.0.0.0'
      - --port
      - '8084'
    depends_on:
      - storage
  storage:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - storage:/var/lib/postgresql/data
volumes:
  storage:
    driver: local