version: "3.3"

services:
  api:
    build: ../../service
    container_name: sandbox-web
    ports:
      - 8084:8084
    command:
      - uvicorn
      - main:app
      - --host
      - '0.0.0.0'
      - --port
      - '80'
volumes:
  storage:
    driver: local