"""adds is_hot column to Technology table

Revision ID: 3c3fbeebaeab
Revises: 6a4b0c9fcae2
Create Date: 2022-04-02 16:55:58.199418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c3fbeebaeab'
down_revision = '6a4b0c9fcae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technology', sa.Column('is_hot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technology', 'is_hot')
    # ### end Alembic commands ###
